### ISSUE TITLE
Unable to save WireGuard configuration Error 

### ISSUE THREAD

**Issue by b0xel** [RaspAP/raspap-webgui#1023]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

When trying to upload a wireguard config file (Mullvad), saving fails with the error: Unable to save WireGuard configuration.
IPV4 only 
## Your environment
1. Operating System: **RPi OS 32-bit Lite** 
2. Hardware and version: RPi 3B+
3. RaspAP version: v2.7.5
4. Followed the project prerequisites? Yes 
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? No

## Steps to reproduce

1- Fresh install of RPi OS 32-bit Lite
2- Update + full upgrade + reboot
3- Set WLAN country 
4- Install RaspAp 
5- upgrade to insiders edition
6- upload wireguard conf file 
![Screenshot_2](https://user-images.githubusercontent.com/22331861/136568289-281980a5-4bd9-4348-8701-100786aedc21.jpg)

**Comment by b0xel** [comment]
They do exist, still having the issue

**Comment by b0xel** [comment]
Yes Linux option. As you said this seems to be a premission issue. Just not sure how to go about fixing it.  trying

**Comment by billz** [comment]
Marking as resolved. Feel free to comment if your issue persists

**Comment by cccaballero** [comment]
Same issue here, @billz sudoers file seems to be ok and I am using the exact same config file that I am using in my desktop PC (Ubuntu)

**Comment by cccaballero** [comment]
I have copied manually the config file to `/etc/wireguard` and is working ok

**Comment by billz** [comment]
Please install the latest release, thx.
