### ISSUE TITLE
Upgrade does not keep the web password

### ISSUE THREAD

**Issue by jeremyfix** [RaspAP/raspap-webgui#1024]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [ ] I checked the FAQ and official documentation before creating this issue
- [ ] I have read and understand the issue reporting guidelines 

## Bug description

After upgrading from 2.6.4 to 2.6.6 (just today), the web password was reset to the default admin/secret while it is said in the install that the config will not change;

This has been already mentioned in the closed issue #629 

## Steps to reproduce

Just do : 

```
curl -sL https://install.raspap.com | bash -s -- --upgrade`
```

**Comment by billz** [comment]
This fix will be available in the next release. Thanks for reporting
