### ISSUE TITLE
RaspAP "Can't connect to network" on Windows 10 

### ISSUE THREAD

**Issue by IAW9927** [RaspAP/raspap-webgui#1043]
## Checklist

- [x ] This is a bug report
- [x ] I have searched this repository for existing issues
- [x ] I checked the FAQ and official documentation before creating this issue
- [x ] I have read and understand the issue reporting guidelines 

## Bug description

The Wi-Fi says on a Windows machine after ~20-45 minutes "Can't conncet to this network", and network says "zero bars signal"
## Your environment
1. Operating System: Raspberry Pi OS
2. Hardware and version: Raspberry Pi 4B (4GB)
3. RaspAP version: 2.6.7
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? No
7. Simultaneous AP and managed mode? Yes
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? NGINX, Kolibri, Kiwix

## Steps to reproduce

Attempt to set as "client AP" mode and then try to connect after 20-45 minutes.

**Comment by billz** [comment]
https://docs.raspap.com/ap-basics/#troubleshooting
