### ISSUE TITLE
Failed to open stream /etc/raspap/hostapd.ini

### ISSUE THREAD

**Issue by Tajnymag** [RaspAP/raspap-webgui#1119]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: RPi OS Lite 11/Bullseye
2. Hardware and version: RPi 3B+
3. RaspAP version: 2.8.4
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes, without OpenVPN and Wireguard
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? No

## Steps to reproduce

a) install a fresh image of RPi OS Lite 11
b) upgrade the system (full-upgrade as told by README)
c) run quick installer and deselect OpenVPN/Wireguard
d) reboot and connect to raspi-webgui wlan
e) open http://10.3.141.1 in browser and login with credentials from README
f) check how the page is rendered and that the file also doesn't exist on the filesystem

## Screenshots

![obrazek](https://user-images.githubusercontent.com/3985946/153291378-33336cb3-f9b8-4ecd-a1eb-41ae37a518c8.png)

## Additional context

OK, my context isn't completely crystal clean.
Firstly: I am connected to a wired 802.1x network by using a configuration and hook from [this](https://forums.raspberrypi.com/viewtopic.php?t=285379) forum post.
Secondly: During the first quick install run, the Pi encountered a kernel panic and I had to forcefully restart it. The second time I ran the installer, the installation went fine. After encountering the errors in the web config, I've also tried to uninstall raspap and install it again. Hasn't solved the issue.

**Comment by billz** [comment]
Your bug report is missing some vital information, including the full error (assuming `Failed to open stream: Permission denied`). 

Your install is incomplete and/or you have other issues with your device. Start with a fresh SD and follow the project prerequisites.

**Comment by Tajnymag** [comment]
I have followed the prerequisites.
I have started with as fresh installation as possible to be even able to connect to the internet.

Where are the error logs located?

**Comment by billz** [comment]
https://docs.raspap.com/ap-basics/#troubleshooting

This is not a troubleshooting forum. https://docs.raspap.com/issues/
