### ISSUE TITLE
Installer default option to reboot does not do as expected

### ISSUE THREAD

**Issue by Jonny1797** [RaspAP/raspap-webgui#1136]
## Checklist

- [ x] This is a bug report
- [x ] I have searched this repository for existing issues
- [x ] I checked the FAQ and official documentation before creating this issue
- [ x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: **RPi OS 32-bit with desktop** 
2. Hardware and version: RPi 3B+ 
3. RaspAP version: RaspAP v2.5.1
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? Yes - doesn't matter

## Steps to reproduce

Install RaspAP with the install script. Don't put in an Option when asked if you want to reboot.

## Additional context

There will be a pull request with a proposed solution. Only changes [y/N] to [Y/n] to not confuse the user about what is going to happen.

**Comment by billz** [comment]
Resolved with #1137, thanks
