### ISSUE TITLE
My AP is a pro at hide-and-seek!

### ISSUE THREAD

**Issue by qaqak** [RaspAP/raspap-webgui#1148]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

I recently installed RaspAP for a VPN router. I changed the SSID and PSK too. The problem is that my AP doesn't show up on my devices

## Your environment
1. Operating System: **Raspberry Pi OS Buster** 
2. Hardware and version: Raspberry Pi 4B
3. RaspAP version: 2.8.3
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick
6. Using default configuration? No
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? Xfce themes

## Steps to reproduce

Install RaspAP

Change SSID and PSK
Restart `hostapd`

**Comment by billz** [comment]
This often happens if you attempt to host an AP on a frequency (channel) that is incompatible with your clients. See the FAQ for help. Please respect this project's issue policy https://docs.raspap.com/issues/
