### ISSUE TITLE
rock 3a armbian Installation error

### ISSUE THREAD

**Issue by shaozhai** [RaspAP/raspap-webgui#1156]
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
invoke-rc.d: initscript dnsmasq, action "start" failed.
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
     Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-04-18 09:44:26 UTC; 39ms ago
    Process: 4640 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
    Process: 4645 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)

Apr 18 09:44:26 rock3a systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Apr 18 09:44:26 rock3a dnsmasq[4645]: dnsmasq: failed to create listening socket for port 53: Address already in use
Apr 18 09:44:26 rock3a dnsmasq[4645]: failed to create listening socket for port 53: Address already in use
Apr 18 09:44:26 rock3a dnsmasq[4645]: FAILED to start up
Apr 18 09:44:26 rock3a systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Apr 18 09:44:26 rock3a systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Apr 18 09:44:26 rock3a systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Setting up netfilter-persistent (1.0.15ubuntu0.21.04.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/netfilter-persistent.service → /lib/systemd/system/netfilter-persistent.service.
Setting up vnstat (2.6-3) ...
Created symlink /etc/systemd/system/multi-user.target.wants/vnstat.service → /lib/systemd/system/vnstat.service.
Setting up iptables-persistent (1.0.15ubuntu0.21.04.1) ...
update-alternatives: using /lib/systemd/system/netfilter-persistent.service to provide /lib/systemd/system/iptables.service (iptables.service) in auto mode
Setting up gamin (0.1.10-6) ...
Setting up libgamin0 (0.1.10-6) ...
Setting up lighttpd (1.4.59-1ubuntu1) ...
Enabling unconfigured: ok
Run "service lighttpd force-reload" to enable changes
Created symlink /etc/systemd/system/multi-user.target.wants/lighttpd.service → /lib/systemd/system/lighttpd.service.
Processing triggers for libc-bin (2.33-0ubuntu5) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.20-1ubuntu3) ...
[ ✓ ok ] 
RaspAP Install: Enabling PHP for lighttpd
Met dependency: fastcgi
Enabling fastcgi-php: ok
Enabling fastcgi: ok
Run "service lighttpd force-reload" to enable changes
RaspAP Install: Creating RaspAP directories
Creating /etc/raspap/networking
Adding /etc/dhcpcd.conf as base configuration
Changing file ownership of /etc/raspap
RaspAP Install: Optimize PHP configuration
[ ⚠ warning ] PHP configuration could not be found.
RaspAP Install: Backing up existing configs to /etc/raspap/backups
[ ✓ ok ] 
RaspAP Install: Cloning latest files from github
Cloning into '/tmp/raspap-webgui'...
fatal: unable to access 'https://github.com/RaspAP/raspap-webgui/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
[ ✘ error ]  Unable to download files from github 
mv: cannot stat '/tmp/raspap-webgui': No such file or directory
[ ✘ error ]  Unable to move raspap-webgui to web root 
[ ✓ ok ] 
[ ✘ error ]  Web root directory doesn't exist 
RaspAP Install: Changing file ownership in web root directory
chown: cannot access '/var/www/html': No such file or directory
[ ✘ error ]  Unable to change file ownership for '/var/www/html' 
RaspAP Install: Creating hostapd logging & control scripts
cp: cannot stat '/var/www/html/installers/*log.sh': No such file or directory
[ ✘ error ]  Unable to move logging scripts 
cp: cannot stat '/var/www/html/installers/service*.sh': No such file or directory
[ ✘ error ]  Unable to move service control scripts 
chown: cannot access '/etc/raspap/hostapd/*.sh': No such file or directory
[ ✘ error ]  Unable change owner and/or group 
chmod: cannot access '/etc/raspap/hostapd/*.sh': No such file or directory
[ ✘ error ]  Unable to change file permissions 
[ ✓ ok ] 
RaspAP Install: Creating lighttpd control scripts
Copying configport.sh to /etc/raspap/lighttpd
cp: cannot stat '/var/www/html/installers/configport.sh': No such file or directory
[ ✘ error ]  Unable to move service control scripts 
Changing file ownership
chown: cannot access '/etc/raspap/lighttpd/*.sh': No such file or directory
[ ✘ error ]  Unable change owner and/or group 
chmod: cannot access '/etc/raspap/lighttpd/*.sh': No such file or directory
[ ✘ error ]  Unable to change file permissions 
[ ✓ ok ] 
RaspAP Install: Copying lighttpd extra config files
Copying 50-raspap-router.conf to /etc/lighttpd/conf-available
awk: cannot open /var/www/html/config/50-raspap-router.conf (No such file or directory)
Creating link to /etc/lighttpd/conf-enabled
Existing 50-raspap-router.conf found. Unlinking.
unlink: cannot unlink '/etc/lighttpd/conf-enabled/50-raspap-router.conf': No such file or directory
Linking 50-raspap-router.conf to /etc/lighttpd/conf-enabled/
[ ✓ ok ] 
RaspAP Install: Moving configuration file to /etc/raspap
cp: cannot stat '/var/www/html/raspap.php': No such file or directory
[ ✘ error ]  Unable to move files to '/etc/raspap' 
chown: cannot access '/etc/raspap/raspap.php': No such file or directory
[ ✘ error ]  Unable change owner and/or group 
RaspAP Install: Applying default configuration to installed services
cp: cannot stat '/var/www/html/config/hostapd.conf': No such file or directory
[ ✘ error ]  Unable to move hostapd configuration file 
cp: cannot stat '/var/www/html/config/090_raspap.conf': No such file or directory
[ ✘ error ]  Unable to move dnsmasq default configuration file 
cp: cannot stat '/var/www/html/config/090_wlan0.conf': No such file or directory
[ ✘ error ]  Unable to move dnsmasq wlan0 configuration file 
cp: cannot stat '/var/www/html/config/dhcpcd.conf': No such file or directory
[ ✘ error ]  Unable to move dhcpcd configuration file 
cp: cannot stat '/var/www/html/config/defaults.json': No such file or directory
[ ✘ error ]  Unable to move defaults.json settings 
Changing file ownership of /etc/raspap/networking//defaults.json
chown: cannot access '/etc/raspap/networking//defaults.json': No such file or directory
[ ✘ error ]  Unable to change file ownership for defaults.json 
Checking for existence of /etc/dnsmasq.d
Copying bridged AP config to /etc/systemd/network
cp: cannot stat '/var/www/html/config/raspap-bridge-br0.netdev': No such file or directory
[ ✘ error ]  Unable to move br0 netdev file 
cp: cannot stat '/var/www/html/config/raspap-br0-member-eth0.network': No such file or directory
[ ✘ error ]  Unable to move br0 member file 
Copying primary RaspAP config to includes/config.php
cp: cannot stat '/var/www/html/config/config.php': No such file or directory
[ ✓ ok ] 
RaspAP Install: Configuring networking
Enabling IP forwarding
net.ipv4.ip_forward = 1
Restarting procps (via systemctl): procps.service.
Checking iptables rules
Adding rule: -t nat -A POSTROUTING -j MASQUERADE
iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
[ ✘ error ]  Unable to execute iptables 
Adding rule: -t nat -A POSTROUTING -s 192.168.50.0/24 ! -d 192.168.50.0/24 -j MASQUERADE
iptables v1.8.7 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
[ ✘ error ]  Unable to execute iptables 
Persisting IP tables rules
Enable RaspAP control service (Recommended)? [Y/n]: y
RaspAP Install: Enabling RaspAP daemon
Disable with: sudo systemctl disable raspapd.service
cp: cannot stat '/var/www/html/installers/raspapd.service': No such file or directory
[ ✘ error ]  Unable to move raspap.service file 
Failed to enable unit: Unit file raspapd.service does not exist.
[ ✘ error ]  Failed to enable raspap.service 
[ ✓ ok ] 
RaspAP Install: Configure ad blocking (Beta)
Install ad blocking and enable list management? [Y/n]: y
RaspAP Install: Creating ad blocking base configuration (Beta)
Creating /etc/raspap/adblock
Fetching latest hostnames list
/tmp/hostnames.txt  100%[===================>]   4.84M  4.21MB/s    in 1.2s    
Fetching latest domains list
/tmp/domains.txt    100%[===================>]  11.63M  7.78MB/s    in 1.5s    
Adding blocklists to /etc/raspap/adblock
Moving and setting permissions for blocklist update script
cp: cannot stat '/var/www/html/installers/update_blocklist.sh': No such file or directory
[ ✘ error ]  Unable to move blocklist update script 
changed ownership of '/etc/raspap/adblock/domains.txt' from root:root to root:www-data
changed ownership of '/etc/raspap/adblock/hostnames.txt' from root:root to root:www-data
chown: cannot access '/etc/raspap/adblock/*.sh': No such file or directory
[ ✘ error ]  Unable to change owner/group 
chmod: cannot access '/etc/raspap/adblock/*.sh': No such file or directory
/tmp/raspap_common.sh: line 316: install_error: command not found
Adding 090_addblock.conf to /etc/dnsmasq.d
Enabling local DNS name resolution for DHCP clients
sed: can't read /etc/dnsmasq.d/090_wlan0.conf: No such file or directory
[ ✘ error ]  Unable to modify  
Enabling ad blocking management option
sed: can't read /var/www/html/includes/config.php: No such file or directory
[ ✘ error ]  Unable to modify config.php 
[ ✓ ok ] 
RaspAP Install: Configure OpenVPN support
Install OpenVPN and enable client configuration? [Y/n]: y
RaspAP Install: Installing OpenVPN and enabling client configuration
Adding packages via apt-get
Reading package lists...
Building dependency tree...
Reading state information...
openvpn is already the newest version (2.5.1-1ubuntu1.1).
openvpn set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 99 not upgraded.
sed: can't read /var/www/html/includes/config.php: No such file or directory
[ ✘ error ]  Unable to modify config.php 
Enabling openvpn-client service on boot
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-client@client.service → /lib/systemd/system/openvpn-client@.service.
RaspAP Install: Creating OpenVPN control scripts
cp: cannot stat '/var/www/html/installers/configauth.sh': No such file or directory
[ ✘ error ]  Unable to move auth control script 
cp: cannot stat '/var/www/html/installers/openvpnlog.sh': No such file or directory
[ ✘ error ]  Unable to move logging script 
chown: cannot access '/etc/raspap/openvpn/*.sh': No such file or directory
[ ✘ error ]  Unable change owner and/or group 
chmod: cannot access '/etc/raspap/openvpn/*.sh': No such file or directory
[ ✘ error ]  Unable to change file permissions 
[ ✓ ok ] 
RaspAP Install: Configure WireGuard support
Install WireGuard and enable VPN tunnel configuration? [Y/n]: y
RaspAP Install: Configure WireGuard support
Installing wireguard from apt
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  linux-image-5.11.0-1027-oracle linux-image-oracle
  linux-modules-5.11.0-1027-oracle linux-modules-extra-5.11.0-1027-oracle
Suggested packages:
  fdutils linux-oracle-doc-5.11.0 | linux-oracle-source-5.11.0
  linux-oracle-tools linux-headers-5.11.0-1027-oracle
Recommended packages:
  flash-kernel | grub-efi-arm64
The following NEW packages will be installed:
  linux-image-5.11.0-1027-oracle linux-image-oracle
  linux-modules-5.11.0-1027-oracle linux-modules-extra-5.11.0-1027-oracle
  wireguard
0 upgraded, 5 newly installed, 0 to remove and 99 not upgraded.
Need to get 71.3 MB of archives.
After this operation, 358 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com hirsute-security/main arm64 linux-modules-5.11.0-1027-oracle arm64 5.11.0-1027.30 [16.3 MB]
Get:2 http://ports.ubuntu.com hirsute-security/main arm64 linux-image-5.11.0-1027-oracle arm64 5.11.0-1027.30 [11.9 MB]
Get:3 http://ports.ubuntu.com hirsute-security/main arm64 linux-modules-extra-5.11.0-1027-oracle arm64 5.11.0-1027.30 [43.1 MB]
Get:4 http://ports.ubuntu.com hirsute-security/main arm64 linux-image-oracle arm64 5.11.0.1027.26 [2,516 B]
Get:5 http://ports.ubuntu.com hirsute/universe arm64 wireguard all 1.0.20210223-1ubuntu1 [3,276 B]
Fetched 71.3 MB in 9s (7,577 kB/s)
Selecting previously unselected package linux-modules-5.11.0-1027-oracle.
(Reading database ... 163772 files and directories currently installed.)
Preparing to unpack .../linux-modules-5.11.0-1027-oracle_5.11.0-1027.30_arm64.deb ...
Unpacking linux-modules-5.11.0-1027-oracle (5.11.0-1027.30) ...
Selecting previously unselected package linux-image-5.11.0-1027-oracle.
Preparing to unpack .../linux-image-5.11.0-1027-oracle_5.11.0-1027.30_arm64.deb ...
Unpacking linux-image-5.11.0-1027-oracle (5.11.0-1027.30) ...
Selecting previously unselected package linux-modules-extra-5.11.0-1027-oracle.
Preparing to unpack .../linux-modules-extra-5.11.0-1027-oracle_5.11.0-1027.30_arm64.deb ...
Unpacking linux-modules-extra-5.11.0-1027-oracle (5.11.0-1027.30) ...
Selecting previously unselected package linux-image-oracle.
Preparing to unpack .../linux-image-oracle_5.11.0.1027.26_arm64.deb ...
Unpacking linux-image-oracle (5.11.0.1027.26) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20210223-1ubuntu1_all.deb ...
Unpacking wireguard (1.0.20210223-1ubuntu1) ...
Setting up linux-image-5.11.0-1027-oracle (5.11.0-1027.30) ...
I: /boot/vmlinuz.old is now a symlink to vmlinuz-4.19.211
I: /boot/initrd.img.old is now a symlink to initrd.img-4.19.211
I: /boot/vmlinuz is now a symlink to vmlinuz-5.11.0-1027-oracle
I: /boot/initrd.img is now a symlink to initrd.img-5.11.0-1027-oracle
Setting up linux-modules-extra-5.11.0-1027-oracle (5.11.0-1027.30) ...

Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(192.168.1.108) at 17:48:52.

Type `help' to learn how to use Xshell prompt.

**Comment by billz** [comment]
https://docs.raspap.com/issues/
