### ISSUE TITLE
Default answer in uninstall script not respected

### ISSUE THREAD

**Issue by fam4r** [RaspAP/raspap-webgui#1159]
## Checklist
- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description
Default answer in uninstall script not respected

## Your environment
1. Operating System: Ubuntu 20.04.4 LTS
2. Hardware and version: Odroid C2

## Steps to reproduce
1. Install with `curl -sL https://install.raspap.com | bash`
2. Uninstall with ([source](https://docs.raspap.com/faq/#how-do-i-uninstall-raspap))
    - `cd /var/www/html`
    - `sudo installers/uninstall.sh`

## Screenshots
Not providing answer (default is NO)

![image](https://user-images.githubusercontent.com/9888550/164891495-c96e757c-ea91-4ad9-9bda-bbf617c9de8a.png)

Providing NO answer

![image](https://user-images.githubusercontent.com/9888550/164891504-c5d23a09-f824-4fca-b27d-ce42c7e7ed62.png)

**Comment by billz** [comment]
See https://github.com/RaspAP/raspap-webgui/commit/a8aa6d4331d0f34ae91a53942c5609f68eee16e7
