### ISSUE TITLE
RaspAP not working with zerotier (and vice versa)

### ISSUE THREAD

**Issue by AleXSR700** [RaspAP/raspap-webgui#1165]
Hello everyone,

I was running zerotier on my system before installing RaspAP. Now that I have RaspAP installed, zerotier is not working anymore.

At first dnsmasq would not start in RaspAP so I executed
`sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo systemctl mask systemd-resolved`

Then dnsmasq started in RaspAP.

But now zerotier is not working.
`sudo zerotier-cli info
Error connecting to the ZeroTier service: 

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
`
Does anybody know how to run both in parallal or whether this is even possible?

I am using wlan0 to connect to router and wlan1 as AP.

Thank you for your support
Alex

**Comment by billz** [comment]
https://docs.raspap.com/issues/
