### ISSUE TITLE
error while install

### ISSUE THREAD

**Issue by WasteEmu77** [RaspAP/raspap-webgui#1177]
RaspAP Install: Backing up existing configs to /etc/raspap/backups
cp: cannot create regular file '/etc/raspap/backups/interfaces.2022-05-29-17:59': No such file or directory
ln: failed to create symbolic link '/etc/raspap/backups/interfaces': No such file or directory
cp: cannot create regular file '/etc/raspap/backups/dhcpcd.conf.2022-05-29-17:59': No such file or directory
ln: failed to create symbolic link '/etc/raspap/backups/dhcpcd.conf': No such file or directory

**Comment by billz** [comment]
#1173
