### ISSUE TITLE
Loosing wifi with VPN connection

### ISSUE THREAD

**Issue by napoleon2121** [RaspAP/raspap-webgui#1180]
Hi. thank you for the nice interface that you made in order to help us make rasberry pi as a hotspot

i hav a small problem. I installed raspAP and i used VPN option in order for these devices to use VPN. 
When i enanle VPN alla devices are loosing connection with the rasberry and even if they connect they doen't hav internet connection. 

any halp appreciated 
thank you in advance

## Checklist

- [ ] This is a bug report
- [ ] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [ ] I checked the FAQ and official documentation before creating this issue
- [ ] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: **ENTER HERE** 
2. Hardware and version: 
3. RaspAP version: 
4. Clean install of a compatible operating system? 
5. RaspAP Quick Install or Manual setup? 
6. Using default configuration? 
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? 
9. Other software or services running with RaspAP?

**Comment by billz** [comment]
https://docs.raspap.com/faq/#openvpn-fails
