### ISSUE TITLE
Authentication Problem Using RaspAp at hotel’s hot spot

### ISSUE THREAD

**Issue by surecom25** [RaspAP/raspap-webgui#1190]
I made RaspAp router with 2 wifi interfaces. One is connected to hotel open wifi network with Hotspot authorization. Hotel wifi system uses ubiquiti equipment.  Every 5 minutes authorization brakes, and need to send authorization form again.

## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

Ubiquiti hot spot Authorization issue, due to 1.1.1.1 internet connection check 
## Your environment
1. Operating System: RPi OS 32-bit 
2. Hardware and version: RPi 4
3. RaspAP version: 2.8.5
4. Clean install of a compatible operating system? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? Yes
8. Onboard wireless chipset or external adapter? Both
9. Other software or services running with RaspAP? 

## Steps to reproduce

I made RaspAp router with 2 wifi interfaces. One is connected to hotel open wifi network with Hotspot authorization, another is AP. Hotel wifi system uses ubiquiti equipment.  Every 5 minutes authorization brakes, and need to send authorization form again.
I found a reason:
HotSpot redirects to some web address to make authorization, this address has IP 1.1.1.1!
I don’t know it is Ubiquity settings or local admin, but it is.
Next is RaspAp checks internet connection every few minutes, and by default it is 1.1.1.1 address.
This means RaspAp initiated authorization every time when checked internet connection. 
The solution: I searched and replaced everywhere in RaspAp files 1.1.1.1 to 8.8.8.8 and one.one.one.one to google.com

## Additional context

This is not full RaspAp fault, but I decided to write this information, maybe it can help to somebody.

**Comment by billz** [comment]
The 1.1.1.1 address is defined in RaspAP's default configuration, which is [documented here](https://docs.raspap.com/defaults/#networking-defaults). All of the default settings may be changed by modifying a single .json file, if you wish. These values are not hard-coded in the application.

> Next is RaspAp checks internet connection every few minutes, and by default it is 1.1.1.1 address

RaspAP doesn't actually do any internet connection checking itself; it queries these static DNS servers each time you view the Networking UI. Again, modify `defaults.json` to whatever values you need. Hope this makes sense.
