### ISSUE TITLE
Integrate Dynamic DNS Support

### ISSUE THREAD

**Issue by DanielLester83** [RaspAP/raspap-webgui#1220]
**Is your feature request related to a problem? Please describe.**
ISPs changing your ip address.

**Describe the solution you'd like**
An integrated setup page for freedns.

for example see: https://freedns.afraid.org/dynamic/

**Describe alternatives you've considered**
A cron command can be added manually at the command line.

**Additional context**
Wireguard and OpenVPN benefit from using Dynamic Dns.

**Comment by billz** [comment]
This could be a good candidate for an extensible plugin architecture https://github.com/RaspAP/raspap-webgui/discussions/1052
