### ISSUE TITLE
High temperature when using RaspAP as AP on a Pi 4 8gB

### ISSUE THREAD

**Issue by tduong-cloud** [RaspAP/raspap-webgui#1228]
I have RaspAp installed on a Raspberry Pi 4 8GB. I have an ethernet cable connected from my router to the Pi.

When connected to the Pi network, and if I am downloading around 40mbps or more, the Pi is getting hot, and my fan would start to run (it is configured to be running when above 80°C).

Is it a known behaviour or do you think there is a bug in my install ?

**Comment by billz** [comment]
This is not a known behavior of this project. See #954 for troubleshooting tips.
You did not use the bug report template so I cannot determine if this is a clean install or not.

Refer to the above issue and resubmit with the issue template if your problem persists.
https://docs.raspap.com/issues/
