### ISSUE TITLE
Feature Request: Support for multiple Wireguard configurations/servers

### ISSUE THREAD

**Issue by neorrk** [RaspAP/raspap-webgui#1231]
I have multiple Wireguard servers that I want to choose from, but each time I have to upload a new .conf file. 

It would be nice if I could upload all of my configs just once and then choose which one I want to use from a list.

**Comment by billz** [comment]
@neorrk great suggestion :) https://docs.raspap.com/wireguard/#multiple-configs

Per our project's sponsorware model, this is available first to Insiders. Since you suggested it I'd be happy to give you free access to the Insiders repo, just say the word

**Comment by neorrk** [comment]
@billz 
"Thank you so much for implementing this feature! I really appreciate it. I'd love to be part of the Insiders and try it out. Looking forward to testing it and providing feedback!"
