### ISSUE TITLE
Missmatch between wireless interfaces in Dashboard page

### ISSUE THREAD

**Issue by nsdoukos** [RaspAP/raspap-webgui#1250]
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

When more than one wireless interfaces are present the start/stop button in Dashboard state reads the state of the interface acting as an AP and the name is that of the wifi_interface_client. Code for start/stop buttton manages the wifi_interface_client. The ifaceStatus that is used to show wlan0 state also changes according to the button value and as a result doesn't show the correct state of the wlan0 interface. I can push a fix if someone explains the correct behaviour.

## Your environment
1. Operating System: Rasbian GNU/Linux 11 (bullseye) 
2. Hardware and version: RPi 3B+ 
3. RaspAP version: 2.8.6 
4. Clean install of a compatible operating system? Yes 
5. RaspAP Quick Install or Manual setup? Quick Install 
6. Using default configuration? Yes  Both 
9. Other software or services running with RaspAP? 

## Steps to reproduce

Go to Dashboard page

## Screenshots

![Screenshot 2022-11-03 at 11-01-03 RaspAP WiFi Configuration Portal](https://user-images.githubusercontent.com/16269556/199683594-e5564f76-c237-45ba-9ed4-556687ac39ec.png)
![Screenshot 2022-11-03 at 11-11-48 RaspAP WiFi Configuration Portal](https://user-images.githubusercontent.com/16269556/199683670-58715689-7b1a-48ec-9954-153a8bbcc376.png)

**Comment by billz** [comment]
Sounds like a bug, I'll look into it. Thanks for reporting.
