### ISSUE TITLE
WiFi slowly around 30-35mbs after connection to RaspAP wifi

### ISSUE THREAD

**Issue by tsvetkovsecurity** [RaspAP/raspap-webgui#1254]
Hello. I have use Raspberry PI 4B+
I have installed fresh RaspAP.

Before Connecting RaspAP - https://www.speedtest.net/result/13938402384
After Connecting RaspAP WiFi - https://www.speedtest.net/result/13938405886

Connection drop around with 25-35 mbps...

Configuration : 802.11n - 2.4ghz
If i use 802.11g - i will drop 50-60mbps.. Better speed i got with 802.11n

Any idea how to up it?

**Comment by billz** [comment]
Duplicate of #454
