### ISSUE TITLE
IP address but No internet

### ISSUE THREAD

**Issue by CristianTacoronteRivero** [RaspAP/raspap-webgui#1259]
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

Good! Forgive my ignorance but I can't solve the following problem.

I have followed all the recommendations to install RasAP, the OS is Raspberry Pi OS 64-bit, I have configured the location, updated everything, the device gets an IP within the established range but does not transmit internet. The raspberry has access to the internet, I have verified it by pinging google.com. Any suggestions? Sorry for the inconvenience caused and thanks for the help!

## Your environment
1. Operating System: **RPi OS 64-bit Lite** 
2. Hardware and version: **RPi 4** 
3. RaspAP version: **Actually**
4. Clean install of a compatible operating system? **Yes**
5. RaspAP Quick Install or Manual setup? **Quick Install**
6. Using default configuration? **Yes**
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? **Onboard**
9. Other software or services running with RaspAP? **IOTstack Docker** 

## Screenshots

![1669275904352](https://user-images.githubusercontent.com/95083694/203724164-a4a54b09-4ed7-40b8-8509-f8c4bf765509.jpg)

**Comment by billz** [comment]
Please respect this project's issue policy and post this as a discussion, thanks

https://docs.raspap.com/issues/
