### ISSUE TITLE
Lease Period doesn't save when changed

### ISSUE THREAD

**Issue by FluffyPunk** [RaspAP/raspap-webgui#1280]
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

That problem is tracked from a lot of versions. So, when you change lease time to infinite and save AND after that you edit some other dhcpd settings, it says that "lease time is not correct, etc., etc.".

## Your environment
1. Operating System: RPi OS 32-bit Lite 
2. Hardware and version: RPi 3B+
3. RaspAP version: v2.8.6
4. Clean install of a compatible operating system? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? No
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? None

## Steps to reproduce

DHCP server settings - Set Lease Time to infinite - Save - Open it again

## Additional context

I'm not expert, but as I understand, lease time is not saved if infinite or something else and it would be great to make it morre comfortable

**Comment by billz** [comment]
Thanks for reporting
