### ISSUE TITLE
Connected Without Internet

### ISSUE THREAD

**Issue by InikoMatthewPro** [RaspAP/raspap-webgui#1290]
## Hardware:
- Raspberry Pi OS 32bit (based-debian 10)
- Raspberry Pi 4

## Raspap Version:
- v2.8.6

## story 
I setup raspap to my raspberry pi 4 and then i change SSID and password on my raspberry pi 4. And now i connect to Raspberry pi 4 wifi but it say "Connected without internet". can you help me how to fix?

**Comment by billz** [comment]
https://docs.raspap.com/issues
