### ISSUE TITLE
Save settings errors with open networks due to lack of password.

### ISSUE THREAD

**Issue by Frostie314159** [RaspAP/raspap-webgui#1291]
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: RPi OS 64-bit Lite 
2. Hardware and version: RPi 4
3. RaspAP version: v2.8.6
4. Clean install of a compatible operating system? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? No

## Steps to reproduce

Create an open WiFi network and save the settings without a password.

**Comment by billz** [comment]
https://docs.raspap.com/faq/#nopw
