### ISSUE TITLE
No internet access

### ISSUE THREAD

**Issue by hex-developer** [RaspAP/raspap-webgui#1307]
## Checklist

- [ ] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: **Raspberry Pi OS 6 4-bit Lite** 
2. Hardware and version:  Raspberry Pi 400
3. RaspAP version:  latest (I can't access the pi now, it has no internet access, but I installed it today)
4. Clean install of a compatible operating system?  Yes
5. RaspAP Quick Install or Manual setup?  Quick Install
6. Using default configuration?  Yes
7. Simultaneous AP and managed mode?  Yes
8. Onboard wireless chipset or external adapter?  Onboard
9. Other software or services running with RaspAP? None

## Steps to reproduce

I started with a fresh install of 64 bit RPi OS.
1. raspi-config -> set wireless lan country
2. apt update and upgrade
3. run raspap quick installer (curl -L https://install.raspap.com | bash)
4. accept defaults (no openvpn or wireguard)
5. reboot
6. connect to the AP from my computer
7. test internet connection: none
8. test dns lookups: they work

**Comment by billz** [comment]
https://docs.raspap.com/issues
