### ISSUE TITLE
Clients have no internet in AP mode (bridge seems to work)

### ISSUE THREAD

**Issue by dgrat** [RaspAP/raspap-webgui#1343]
## Your environment
1. Operating System: RPi OS 32-bit Lite
2. Hardware and version: Tested with RPi3 internal and external wifi0/wifi1 and RPi 1 with external
3. RaspAP version: current
4. Clean install of a compatible operating system? Yes
5. RaspAP Quick Install or Manual setup? Quick
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? I don't know (standard)
8. Onboard wireless chipset or external adapter? Yes with RPi3
9. Other software or services running with RaspAP? No

## Steps to reproduce
Just according to the website, download and execute the script, always pressing enter

## Additional context
Used the RPi Image Tool and prepared a fresh installation. 
Clients see internet via eth0 only in bridged mode (this mode seems to work). 
The RPi has internet access always (this also works). 
I think the issue might be related with dnsmasq, because I can't restart the service and my IP is odd. 
It seems to be reproducible, because I did it on two machines.

**Comment by billz** [comment]
https://docs.raspap.com/issues
