### ISSUE TITLE
Wi-Fi information not showing on Web-GUI

### ISSUE THREAD

**Issue by samcallen** [RaspAP/raspap-webgui#1368]
## Checklist

- [x] This is a bug report [x]
- [x] I observed this bug on a clean install of the OS [x] 
- [x] I have followed the project prerequisites [x]
- [x] I have searched this repository for existing issues [x]
- [x] I checked the FAQ and official documentation before creating this issue [x]
- [x] I have read and understand the issue reporting guidelines [x]

## Bug description
Wi-Fi information on GUI shows nothing 

## Your environment
1. Operating System: **RPI OS 32-bit Lite** 
2. Hardware and version: Raspberry Pi 4 Model B Rev 1.4
3. RaspAP version: RaspAP v2.9.2
4. Clean install of a compatible operating system?  Yes
5. RaspAP Quick Install or Manual setup? Quick Install/Manual 
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter?  Onboard
9. Other software or services running with RaspAP? No

## Steps to reproduce

My raspapd.service seems to be starting the uap0 interface on ExecStart, but I don't have it because I am using eth0 (Internet) and wlan0 for (hotspot).The scripts (/etc/raspap/hostapd/servicestart.sh) 

seemed to be starting uap0 towards the end with Ifconfig up uap0. Why is it focusing on the interface I don't have? Could that be what's causing the problem?

## Additional context

Wlan0 ip range  is 10.3.141.0/24
![CamScanner 07-27-2023 03 17_1](https://github.com/RaspAP/raspap-webgui/assets/65163697/2c94e1bc-7fa6-45b0-81d8-910815df58fe)
![CamScanner 07-27-2023 03 14_1](https://github.com/RaspAP/raspap-webgui/assets/65163697/cbe60461-a5f3-4e6b-af29-1d29b2fd5859)

**Comment by billz** [comment]
As the name suggests, the dashboard widget displays info about a configured wireless client - not your AP. 
The raspapd.service only manipulates uap0 if [AP-STA mode is enabled](https://docs.raspap.com/ap-sta/#when-to-reboot).
