### ISSUE TITLE
Hotspot on eth0

### ISSUE THREAD

**Issue by singersbalm** [RaspAP/raspap-webgui#1402]
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description
I tried setting up my raspberry pi similarly to a Fritz box WiFi thingies that enhance the WiFi range. Receiving over WiFi and sending out WiFi while having a lan port. WiFi hotspot works fine, but a lan hotspot does not work. It has the option for eth0 in hotspot but nothing happens when I select it. I can't change the options like(allowing internet connection). My guess is that hotspot is just for WiFi forwarding and the eth ports shouldn't show up. It would be nice if someone could explain how to do it.

## Your environment
1. Operating System: raspberry pi os
2. Hardware and version: 3b
3. RaspAP version: latest
4. Clean install of a compatible operating system? Yes
5. RaspAP Quick Install or Manual setup? Quick
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? External
9. Other software or services running with RaspAP? No

## Steps to reproduce

Selecting eth0 on hotspot.

**Comment by billz** [comment]
Please read the issue policy and start a discussion instead.
