### ISSUE TITLE
reboot w/ WebUI -> WebUI Connection broken -> page reload -> send form data again -> another reboot

### ISSUE THREAD

**Issue by PAINKILLER0928** [RaspAP/raspap-webgui#1410]
## Checklist

- [X] This is a bug report
- [X] I observed this bug on a clean install of the OS
- [X] I have followed the project prerequisites
- [X] I have searched this repository for existing issues
- [X] I checked the FAQ and official documentation before creating this issue
- [X] I have read and understand the issue reporting guidelines 

## Bug description

I encountered follwing beheaviour with the WebUI, I don't know if it is wanted this way.

I reboot the whole system with "System" -> "Reboot"

The browser tells me "Connection failed", with a button "try again"

When clicking on "try again", after the system is back up, Firefox wants to re-submit the form data, which causes the system to reboot again.

I guess the the reboot command is submitted again.
--> input type="submit" class="btn btn-warning" name="system_reboot"   value="Reboot" in the page source code

URL in the browser stays at http://ip.of.the.system:used_port/system_info

You have to manually change the URL to the root path... --> http://ip.of.the.system:used_port/

Then the WebUI is accessible again.

## Your environment
1. Operating System: RPi OS 32-bit Lite
2. Hardware and version: 3B+
4. RaspAP version: V2.9.5
5. Clean install of a compatible operating system? --> Yes
6. RaspAP Quick Install or Manual setup? Quick install with curl
7. Using default configuration? --> No, port for WebUI changed to 10000, installed without OpenVPN and AdBlock
8. Simultaneous AP and managed mode? --> No
9. Onboard wireless chipset or external adapter?  --> Onboard
10. Other software or services running with RaspAP?  --> No

## Steps to reproduce

Like said, it's reproducable behaviour, Browser used: Firefox 118.0.1 on Win 11

**Comment by billz** [comment]
These system buttons have needed attention for awhile. Thanks for raising this
