### ISSUE TITLE
AdBlock not working :/

### ISSUE THREAD

**Issue by NBSUKLTD** [RaspAP/raspap-webgui#1444]
Adblock does not seem to work at all. Have followed all instructions to the letter. 

log file is not helpful and DNS in Dns logging is also on.

Nov  5 14:58:11 dnsmasq[15824]: using only locally-known addresses for domain zzyytt.top
Nov  5 14:58:11 dnsmasq[15824]: using only locally-known addresses for domain zzycj.com
Nov  5 14:58:11 dnsmasq[15824]: using only locally-known addresses for domain zzyanhushi.com
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzzzz13677.com
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzzyyzzzyyyzyyzyyyzzyyzyzzzzzzzzyyzzyyyyyzyzyyzzyzpol7196.cmkaarten.nl
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzzregsizzz.com.ru
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzz8cd.codesandbox.io
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzz.alie3ksgdd.com
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzyytt.top
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzycj.com
Nov  5 15:50:04 dnsmasq[22950]: using only locally-known addresses for domain zzyanhushi.com

**Comment by billz** [comment]
To assist us with troubleshooting, please [read this](https://docs.raspap.com/issues/) and resubmit your issue. Thanks
