### ISSUE TITLE
[Bug]: Network Interfaces

### ISSUE THREAD

**Issue by BliNeR-KeY** [RaspAP/raspap-webgui#1459]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Other

### RaspAP version

3.0 (Latest)

### Other software or services running with RaspAP?

Yes (specify below)

### Bug description

hello i'm using first time RaspAp in my mini server 
i installed by script but i see raspap make my local as virtual have no sence change local network..
coz everyone have open port firewalls etc.

maybe have setting to invert it put raspap as virtual ?. have no sense raspap using my local network and change it..
i think need create own virtual network

192.168.10.75 = local
192.168.10.xxx = virtual

![image](https://github.com/RaspAP/raspap-webgui/assets/22597684/22927328-65ff-4a8d-b24b-a7906eff7577)

### Steps to reproduce

extra setting

**Comment by billz** [comment]
This doesn't appear to be related to a bug. Your debug log (did you generate one?) should answer your question.
If you have a general question or suggestion please use discussions. Thanks.
