### ISSUE TITLE
[Bug]: Insiders, blank screen when uploading Wireguard .config file

### ISSUE THREAD

**Issue by ritchieau1** [RaspAP/raspap-webgui#1490]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 5

### RaspAP version

3.0 (Latest)

### Other software or services running with RaspAP?

Yes (specify below)

### Contact details (optional)

r.u.martini@gmx.de

### Bug description

since more versions after a clean install of Insiders when trying to upload a .config file into Wireguard I get a blank screen, the upload does not occur.

### Steps to reproduce

several attempts to upload .config files in Wireguard show same blank screen

**Comment by billz** [comment]
@ritchieau1 thanks for reporting this
