### ISSUE TITLE
cannot start quick installer

### ISSUE THREAD

**Issue by w45354** [RaspAP/raspap-webgui#1505]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.0 (Latest)

### Other software or services running with RaspAP?

Not sure

### Contact details (optional)

453548888@qq.com

### Bug description

I follow the guide step by step, but when I type curl -sL https://install.raspap.com | bash, the quick installer cannot be launched
![d359266519f8b2de093fbdcd9c33461](https://github.com/RaspAP/raspap-webgui/assets/157502002/2e1fb92d-e1df-4d87-9275-578f146a3f3a)
.

### Steps to reproduce

I am in China, so I set the WLAN location to CN. And no VPN is set up in my RPI 4B. Normally, accessing foreign webs like GitHub is prohibited in China, I am wondering if this causes me to get no access to raspap's server, leading to a failure to launch a quick installer.

### Screenshots

![d359266519f8b2de093fbdcd9c33461](https://github.com/RaspAP/raspap-webgui/assets/157502002/72f80ee3-3352-4c51-b630-3cca8d6493cd)

**Comment by billz** [comment]
See https://github.com/RaspAP/raspap-webgui/discussions/1492#discussioncomment-8021446

**Comment by w45354** [comment]
I cannot get access to Raspap's server because I am in China, and I am trying to install it manually I also cannot connect to the service as github is blocked in China. do you have any solutions if I would like to install RaspAP in china?
![533719ff1e3cfc009865cd09069dfd5](https://github.com/RaspAP/raspap-webgui/assets/157502002/b69a9570-df53-407b-9fb1-6a47127f45f4)

**Comment by billz** [comment]
You could run the installer locally, for example `./installers/raspbian.sh` but this first requires that you have the project from GitHub. If you are unable to access the installer due to it being blocked, you won't be able to clone files from GitHub. 

According to our stats, China is the third most popular country for RaspAP installs. So users must be able to obtain it some other way. Have you tried a GitHub mirror?

**Comment by w45354** [comment]
I can download files from GitHub from my PC as a VPN client is installed. Now I already have the project files in my RPI, but I don't know how to set it up by the command codings, do you have any guidelines?
