### ISSUE TITLE
Add option to configure the firewall for IPTables or NFTables

### ISSUE THREAD

**Issue by Oak-Trees** [RaspAP/raspap-webgui#1512]
## Is your feature request related to a problem? 
I installed Raspap on a Raspberry Pi running Raspberry Pi OS 12 - Bookworm. Bookworm comes with NFTables, not IPTables.

## Describe the solution you'd like
An option to select in the install script to use IPTables or NFTables would be nice, or detecting automatically which firewall is installed and configure the correct one.

**Comment by billz** [comment]
nf_tables is the default backend when using iptables. the latter is still present in bookworm, so...

```
iptables -v
iptables v1.8.9 (nf_tables)

lsb_release -d
Debian GNU/Linux 12 (bookworm)
```
