### ISSUE TITLE
[Bug]: RaspAP has no internet. Raspberry Pi Bookworm now has NFTables not IPTables

### ISSUE THREAD

**Issue by Oak-Trees** [RaspAP/raspap-webgui#1513]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.0 (Latest)

### Other software or services running with RaspAP?

Yes (specify below)

### Bug description

Installed RaspAP and Pi-hole and Unbound on my Raspberry Pi using Apt-get. It's running Debian 12 Bookworm (Raspberry Pi version).
While I was installing RaspAP i saw that tried to add rules to IPTables, but the new Raspberry Pi OS comes with NFTables. I'm guessing this is why my RaspAP works great but doesn't provide internet.

I don't knew enough about firewalls and what the rules are and how they should be added. I hope somebody here can help?

### Steps to reproduce

Install RaspAP using the bash install script in Raspberry Pi OS version Bookworm. Set up the access point using the website.

**Comment by billz** [comment]
See https://github.com/RaspAP/raspap-webgui/issues/1512#issuecomment-1925919260

**Comment by billz** [comment]
The reason you do not have internet is unrelated to nftables. See the FAQ on Pi-hole.
