### ISSUE TITLE
[Bug]: Wireless LAN is not working.

### ISSUE THREAD

**Issue by zerozmask** [RaspAP/raspap-webgui#1524]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.0 (Latest)

### Other software or services running with RaspAP?

No other software

### Bug description

I've tried many different ways and followed the guidelines to setup Wireless LAN feature but cannot establish an internet connection via ethernet to any device so far.

### Steps to reproduce

Fresh install of RaspAP on Raspberry pi 4 b on the Raspberry Pi OS. Now, from RaspAP's Networking > WLAN Routing tab, choose your wireless client interface and output interface (typically, eth0 or enx). Select the "Configure a static IP address and DHCP for output interface" option toggle, choose Save settings and lastly Start WLAN routing. my output is eth0. No internet is accessible on that line.

### Screenshots

![image](https://github.com/RaspAP/raspap-webgui/assets/160825363/075a8b35-8d5e-45e6-8016-a887a101b6b8)
![image](https://github.com/RaspAP/raspap-webgui/assets/160825363/15868dc6-57f6-4e37-ae2d-8e77da67cdfb)

### Additional context

I'm not internet networking adept. It is possibly a simple fix. I've toggled and restarted about every option and ensured the ethernet connection is valid.

**Comment by billz** [comment]
Set the "Configure a static IP address and DHCP for output interface" option (appears disabled in your screenshot) and restart WLAN routing. This is optional as you are also able to configure this yourself in the **DHCP server** UI.
