### ISSUE TITLE
[Bug]: expressvpn doesnt show correct status

### ISSUE THREAD

**Issue by frankozland** [RaspAP/raspap-webgui#1592]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 5

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

No other software

### Contact details (optional)

frankoz95967943@gmail.com

### Bug description

expressvpn doesnt show correct status
expressvpn doesnt show up in routing tables correctly
![image](https://github.com/RaspAP/raspap-webgui/assets/159714444/72b29515-6876-4b36-a004-5d5c77ba50bf)

### Steps to reproduce

disconnect expressvpn button

### Screenshots

![image](https://github.com/RaspAP/raspap-webgui/assets/159714444/47059c01-c1cd-4ff9-a299-37ef262d9c80)
![image](https://github.com/RaspAP/raspap-webgui/assets/159714444/2f56d7e6-9e87-4483-83f5-90c51448f1bc)

**Comment by billz** [comment]
The indicator is stale, ie., refreshing the page will indicate the current status.
