### ISSUE TITLE
Enable BBR by default for speed improvement

### ISSUE THREAD

**Issue by frankozland** [RaspAP/raspap-webgui#1624]
## Is your feature request related to a problem? 
Default TCP scheduler in Rasperry pi is pfifo_fast. this is great for edge use case of single user process space.
RaspAP is more of a router type use case.

## Describe the solution you'd like
On install - 

sysctl net.core.default_qdisc=fq
sysctl net.ipv4.tcp_congestion_control=bbr
sysctl -p

## Additional context
https://www.slideshare.net/slideshow/tcp-and-bbr/89242607#30
![image](https://github.com/user-attachments/assets/78ae7a13-7180-4efb-9ecc-58e1eca7c146)

**Comment by frankozland** [comment]
let me run a few more tests

**Comment by billz** [comment]
Nice idea, I'd like to see the results of your tests. Thanks for the suggestion

**Comment by billz** [comment]
@frankozland this option will be available in the next general release. thanks!
