### ISSUE TITLE
[Bug]: openvpn log only shows 200 lines vs the last 200 lines

### ISSUE THREAD

**Issue by frankozland** [RaspAP/raspap-webgui#1626]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bullseye

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

External adapter

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

Yes (specify below)

### Contact details (optional)

frankoz95967943@gmail.com

### Bug description

https://github.com/frankozland/raspap-webgui/pull/1
updated the script to get the tail of the log for openvpn

### Steps to reproduce

go to openvpn, turn on log, save settings and the log doesnt display the actual tail of the log file.

### Additional context

see issue

**Comment by billz** [comment]
The default log length can be modified in the System menu.
