### ISSUE TITLE
[Bug]: ovpn config filenames with brackets doesn't work

### ISSUE THREAD

**Issue by jimmyjones2** [RaspAP/raspap-webgui#1661]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi Zero W

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

No other software

### Bug description

I've tried to upload openvpn config file `profile-openvpn(6).ovpn` but this caused errors in the UI and the config wasn't added.

It looks as if filenames are not escaped/quoted in the shell commands within the PHP causing the failure, e.g. https://github.com/RaspAP/raspap-webgui/blob/master/includes/openvpn.php#L131 (and another few instances within the same file)

### Steps to reproduce

Upload openvpn profile with filename `profile-openvpn(6).ovpn`

**Comment by billz** [comment]
@jimmyjones2 thanks for reporting
