### ISSUE TITLE
[Bug]: Raspap debian on x86

### ISSUE THREAD

**Issue by frankozland** [RaspAP/raspap-webgui#1672]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Debian	Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

External adapter

### Hardware

Other

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

No other software

### Contact details (optional)

frankoz95967943@gmail.com

### Bug description

Hey Bill - im going to be building out debian on x86 - I know its experimental/beta.
I'll capture issues in this issue as i go thru.

I've already gone thru 1 install already - and it didnt work as expected, but i didnt capture the errors.  this time i will and include them below._

Because of my distance i really need top performance out of WG/openvpn -direct wire removes some latency/problems - it would be very nice if raspap could support direct wire connection.  (ethernet wan -> raspap w/vpn -> lan)

I noticed wg on a full metal computer runs circles around the raspberry in terms of performance (i got over 150mbs on wg even being 8000 miles away from egress point)

I am going to try again and see if i can configure back end to support ethernet directly as other side of masquerade.

### Steps to reproduce

see above

**Comment by billz** [comment]
@frankozland sounds fine, and I agree there are performance gains to be found here. Would you mind creating a new issue with the feature request template and closing this one? Thanks
