### ISSUE TITLE
[Bug]: Eth0 enable fallback to static option not working in the qui

### ISSUE THREAD

**Issue by assachs** [RaspAP/raspap-webgui#1683]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 4 Model B

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

No other software

### Bug description

I want to achieve the following:
- if eth0 is connected to a network with a dhcp server, the ip-address provided by this server should be used
- if eth0 is connected to a network without a dhcp server, a fallback ip-address should be used and a dhcp-server should be startet

At the moment I am failing on the gui.
Under DHCP Server i select eth0,  "DHCP" and "Enable fallback to static option". But i can't insert the static parameters, because the fields are desabled.
Also "DHCP Options" are not enabled.

I'm not sure if "DHCP Options" should work, but at least i would expect, that the "static ip options" should be enabled.

### Steps to reproduce

Go to DHCP-Server
select eth0
select dhcp
enable "enable fallback to static option"
-> static ip options are disabled

**Comment by billz** [comment]
A network interface can either have a static IP address or be assigned one by DHCP. If you select 'DHCP' in the UI, the fallback to static option becomes available. You may then configure a static IP:

<img width="497" alt="image" src="https://github.com/user-attachments/assets/29393af0-c9e6-46ad-87ca-81ec5087173c">

The DHCP fields are disabled because a static IP address is required for this option. This is clearly indicated in the UI.

<img width="497" alt="image" src="https://github.com/user-attachments/assets/afefb8e0-b61c-4b33-85c2-aed18019a37e">

**Comment by assachs** [comment]
To fallback:
i can't edit the IP field if dhcp and fallback is selected.

![image](https://github.com/user-attachments/assets/7dac64ed-38ad-4f8b-9922-981c078828f5)

To DHCP-Server (maybe this is not a bug but a feature request):
if i edit the configuration files manually, i can add a dhcp server if the fallback ip is used. But this cannot be done with the gui.

(as far as i know, dnsmasq is only  responding to dhcp requests if the interface is part of the network of the range. That means it's only responding if the fallback ip is used (or if the ip address received by dhcp is in the same network as the fallback ip)

**Comment by billz** [comment]
I see what you mean. The static IP fields should be enabled when the fallback option is selected.
