### ISSUE TITLE
mac address filter ?

### ISSUE THREAD

**Issue by defaliz** [RaspAP/raspap-webgui#702]
Hi,
thanks for the good product raspap-webgui
is there a way to filer mac address on hostap ?
i use deny_mac_file=/etc/hostapd/hostapd.deny in hostap.conf that works, but when i restart hostap with webgui my configuration is lost..

regards
Alain

**Comment by billz** [comment]
Mac address filtering is not currently supported, although it would be a good advanced setting for hostapd.

**Comment by defaliz** [comment]
thanks Billz, 
yes it will be a good idea for the futur version..
regards

**Comment by pierrepo** [comment]
This would be very useful indeed!

**Comment by AgentBlade4** [comment]
This would be so good because I need it to be open for my DS but I want some security

**Comment by billz** [comment]
This has been implemented in #1666 and will be available in the next release.

**Comment by billz** [comment]
Relevant doc link https://docs.raspap.com/ap-basics/#custom-user-settings
