### ISSUE TITLE
2 different DHCP IP allocated to eth0

### ISSUE THREAD

**Issue by mrespin** [RaspAP/raspap-webgui#724]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I am not sure what is it. RASPAP received two IP from local DHCP.
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 4a:7a:36:01:19:6d brd ff:ff:ff:ff:ff:ff
    inet **10.0.200.236**/24 brd 10.0.200.255 scope global dynamic noprefixroute eth0
       valid_lft 85858sec preferred_lft 85858sec
    inet **10.0.200.227**/24 brd 10.0.200.255 scope global secondary noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8429:7a01:5ea4:ab26/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
GUI can be accessed on both IP, plus on the HotSpot

**Your environment**
* Rock Pi S 1GB NAND Wifi/BT 
* OS: Armbian_20.11_Rockpi-s_buster_legacy_4.4.243_minimal
* image URL: https://www.armbian.com/radxa-rockpi-s/
* Armbian version Buster minimal
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Install: curl -sL https://install.raspap.com | bash
* Using default configuration? (Y)
* Onboard wireless chipset. 
* Other software or services running with RaspAP - No

**Steps to reproduce**
Set Adapter IP Address Settings for eth0 DHCP 
Enable Fallback to Static Option Disabled

**Actual behaviour**
2 local IP, both working the same

**Additional context**
I am very interested in this issue as I want to have RaspAP to be VPN between eth0 and eth0. This problem opens a door for it, Is it possible?

**Comment by billz** [comment]
There is an active pull request #704 that addresses this. Perhaps you can contribute to testing?
