### ISSUE TITLE
Can't connect to a Wifi with wlan0 after stopping the hotspot.

### ISSUE THREAD

**Issue by varshard** [RaspAP/raspap-webgui#736]
**Describe the bug**

wpa_supplicant not started automatically after the hotspot is stopped.

**Your environment**                            
* Raspberry Pi hardware (examples: Pi 3 Model B+    , Pi Zero W) : Pi 4 Model B+
* Raspbian version (examples: RPi OS Lite, Armbi    an): RPi OS Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? Quick In    stall
* Using default configuration? Y
* Simultaneous AP and managed mode? Y
* Onboard wireless chipset or external adapter?     onboard

**Steps to reproduce**

1. Install raspap-webgui using the quick install method with Y for every questions.
2. Reboot and start the hotstpot.
3. RP OS shown that there's no wireless interface.
4. Go to raspi-config > Localization Options > L4 WLAN Country.
5. raspi-config shown message that it can't communicate with wpa_supplicant.
6. start wpa_supplicant manually to make the wireless interface work again.
    ```bash
        wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0
    ```

**Expected behavior**

I'm expecting that stopping hotspot via the webui will stop hostapd and start wpa_supplicant automatically.

**Actual behavior**

wpa_supplicant doesn't started automatically after the hotspot has been stopped and caused RP OS to not be able to connect to a wifi network.

**Additional context**

May be the FAQ should explain how to re-enable wpa_supplicant again after the hotspot has been stopped. I had search around to find that wpa_supplicant isn't working.

**Comment by billz** [comment]
There is a FAQ that addresses this issue specifically https://github.com/billz/raspap-webgui/wiki/FAQs#scanning

Worth noting this only appears to be an issue with RPi OS. Last I checked Armbian exhibited no such behavior. RaspAP could try to detect a busy/failed state and reinitialize wpa_supplicant for the user, but this is putting a band-aid on the problem. It's irritating, I agree, but would rather see the core issue addressed.
