### ISSUE TITLE
[GUI] Dashboard GUI shows wrong wifi adapter state and stopping doesn't do anything

### ISSUE THREAD

**Issue by rusagent** [RaspAP/raspap-webgui#763]
* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ and Wiki before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
When turning off wlan0 via `ifconfig wlan0 down`, which was the unused rasperry pi 4 internal wifi chip, i still can see "Stop wlan0" in the webgui's dashboard like seen in the picture. Should i just make a branch and try to fix it? I pretty much folllowed this guide: https://www.bitblokes.de/vpn-router-mit-raspberry-pi-raspap-und-nordvpn-openvpn-einfach/

**Your environment**
 - Raspberry Pi 4b
 - PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
 - RaspAP v2.5.2
 - Followed the project prerequisites? (Y)
 - Checked the project FAQ? (Y)
 - RaspAP Quick Install 
 - Using default configuration? (N)
 - Simultaneous AP and managed mode? (N)
 - external adapter
 - Other software or services running with RaspAP: NordVPN wiht nordlynx adapter

set up raspap with quickinstall and norvpn with nordlynx. i pretty much followed the guide at the top but i use wlan1.

**Expected behavior**
The button in the GUI shows "Start wlan0"

**Actual behavior**
The button shows "Stop wlan0"

**Screenshots**

![image](https://user-images.githubusercontent.com/1582815/104670217-b934bd80-56db-11eb-9a54-7e9a27fa99f5.png)

**Comment by billz** [comment]
Yep, sounds like a bug. 

> Should i just make a branch and try to fix it? 

That'd be great, thanks :)
