### ISSUE TITLE
WPA2-Enterprise to WPA2 AP

### ISSUE THREAD

**Issue by MrDrache333** [RaspAP/raspap-webgui#819]
* [ *] This is a bug report
* [ *] I searched existing issues before opening this one
* [ *] I checked the FAQ and Wiki before creating this issue
* [ *] I have read and understand the issue reporting guidelines 

**Describe the bug**
Ive managed to get wlan1 connected to a WPA2-ENterprise WLan (FREE-RADIUS) but if I put the HotSPot on the same Channel and set it to `AP-Mode from WiFI-Client` the uap0 Interface won't get up. If I configure the hotspot without the AP-Mode from WiFi-CLient it works just fine.

**Your environment**
Raspi3b+ with latest Release of RaspAP (As of today) and everything up to date.
Extra Hardware: Edimax EW7612UAn V2

**Steps to reproduce**
Connect with the Edimax (wlan1) to a FreeRadius WPA2-Enterprise Network and try to open a HotSpot in AP-Mode from WIFI-Client

**Expected behavior**
The HotSpot should go up and I can connect with my WPA2-Network and get internet trough the WPA2-Enterprise network

**Actual behavior**
The Hotspot stays down

**Screenshots**
<img width="694" alt="Bildschirmfoto 2021-03-08 um 14 36 17" src="https://user-images.githubusercontent.com/22854641/110328611-d8850280-801b-11eb-8570-df18a14b2513.png">
<img width="419" alt="Bildschirmfoto 2021-03-08 um 14 35 59" src="https://user-images.githubusercontent.com/22854641/110328614-da4ec600-801b-11eb-8406-6e172cc44ecb.png">

**Additional context**
hostapd Log:
Configuration file: /etc/hostapd/hostapd.conf (Default)
Could not read interface uap0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=uap0 disabled_11b_rates=0
Could not read interface uap0 flags: No such device
nl80211 driver initialization failed.
uap0: interface state UNINITIALIZED->DISABLED
uap0: AP-DISABLED 
uap0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface uap0 wasn't started

**Comment by billz** [comment]
You are misusing AP-STA mode. With two wireless adapters, configure one as the client (as you've done already) and select the other interface for the AP side. 

https://docs.raspap.com/faq/#interfaces

**Comment by MrDrache333** [comment]
As described above, i did exactly what you said. The Problem is, that RaspAP is not able to create a Hotspot of a WPA2-Enterprise.

WLan0 as Client and wlan1 as AP.

**Comment by billz** [comment]
This security type is unsupported. Search the issues, it's already been requested several times.
