### ISSUE TITLE
Unable to install Insider.

### ISSUE THREAD

**Issue by ledge39** [RaspAP/raspap-webgui#821]
**Before submitting an issue**

All submitters MUST read this first https://docs.raspap.com/issues/

Have a question or want to suggest a feature? Start or join a discussion https://github.com/raspap/raspap-webgui/discussions

* [ ] This is a bug report
* [ ] I searched existing issues before opening this one
* [ ] I checked the FAQ and Wiki before creating this issue
* [ ] I have read and understand the issue reporting guidelines 

**Describe the bug**

**Your environment**
* Raspberry Pi hardware - Pi 3 Model B+  
* Raspbian version - RPi OS Lite
* RaspAP version (reported by the Quick Installer) 
* Followed the project prerequisites?  y
* Checked the project FAQ?  y
* RaspAP Quick Install 
* Using default configuration?   y
* Simultaneous AP and managed mode?  y
* Onboard wireless chipset

I have run the following:-

curl -sL https://install.raspap.com | bash -s -- --upgrade --insiders

![Screenshot 2021-03-09 at 18 15 02](https://user-images.githubusercontent.com/37451439/110518475-0a719400-8104-11eb-92aa-62bc50a9def4.png)

The does not appear to beable to connect to Github directory. I have sponsered the project, so I believe it should work, please help.

**Comment by billz** [comment]
Hi @ledge39, you should have received an invitation to Insiders, which gives you access to the private repo. Your invitation still has a pending status, so check for a notification from GitHub.

**Comment by ledge39** [comment]
Thanks. I was being impatient .
