### ISSUE TITLE
losing inet after reconnecting LAN

### ISSUE THREAD

**Issue by vahidx4r4x** [RaspAP/raspap-webgui#822]
Hi
thank you for your awesome project. I noticed a problem with forwarding traffic.
i sat up RaspAP and configured everything and its working flawlessly but whenever I unplug and reconnect the LAN port, internet traffic disappears. i can login to RaspAP and i am able to ssh into raspberry pi and everything is fine but i lose internet connection and i should reboot the raspberry pi by command or reconnecting power.
what is the problem?

**Comment by billz** [comment]
Please resubmit your issue with the provided template. See https://docs.raspap.com/issues/
