### ISSUE TITLE
losing inet after reconnecting LAN

### ISSUE THREAD

**Issue by vahidx4r4x** [RaspAP/raspap-webgui#827]
**Before submitting an issue**

All submitters MUST read this first https://docs.raspap.com/issues/

Have a question or want to suggest a feature? Start or join a discussion https://github.com/raspap/raspap-webgui/discussions

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ and Wiki before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Hi
thank you for your awesome project. I noticed a problem with forwarding traffic.
i sat up RaspAP and configured everything and its working flawlessly but whenever I unplug and reconnect the LAN port, internet traffic disappears. i can login to RaspAP and i am able to ssh into raspberry pi and everything is fine but i lose internet connection and i should reboot the raspberry pi by command or reconnecting power. I am using built-in openvpn 

**Your environment**
* Raspberry Pi hardware (Raspberry Pi 4 2GB)  
* Raspbian version (RPi OS Lite)
* RaspAP version (2.6.3) 
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? QUICK
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (N)
* Onboard wireless chipset or external adapter? ONBOARD
* Other software or services running with RaspAP? NO

**Steps to reproduce**
Tell us how to reproduce this issue. Provide as much detailed information as possible.

**Expected behavior**
RECONNECT TO THE VPN AND REFORWARD ALL THE TRAFFIC

**Actual behavior**
EVERYTHING LOOKS FINE BUT I DONT HAVE INTERNET CONNECTION.

**Screenshots**

**Additional context**

**Comment by billz** [comment]
> whenever I unplug and reconnect the LAN port, internet traffic disappears

Protip: stop OpenVPN (and any related services) before unplugging `eth0`, then restart it after you've reconnected it.
