### ISSUE TITLE
AP-STA + VNC: No route to the host is know

### ISSUE THREAD

**Issue by bocangr** [RaspAP/raspap-webgui#832]
## Checklist

- [x] This is a bug report
- [x ] I have searched this repository for existing issues
- [x ] I checked the FAQ and official documentation before creating this issue
- [x ] I have read and understand the issue reporting guidelines 

## Bug description
Hi,

I have installed RaspAP on my Raspberry and configured it to work as a AP-STA. The idea is to connect the Raspberry to an external network while creating another network to connect some IoT devices. To make the configuration easier, I wanted to connect my laptop to this own RPi-created network through RealVNC (VNC Viewer on Laptop + VNC server on RPi). The problem I have is that, when I try to connect to the RPi, I get a message stating that "No route to the host is known":

![Captura](https://user-images.githubusercontent.com/81161791/112169696-b7630b00-8bf2-11eb-863e-db9a2d0595ec.PNG)

I am trying to to connect it through the IP address 192.168.50.1, which is the one I get under the uap0 interface in ifconfig

1. Operating System: RPi OS 32-bit Full
2. Hardware and version: Raspberry Pi 3B+
3. RaspAP version: v2.6.3
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install 
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? Yes
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? VNC Server

**Comment by connected201** [comment]
hi, try to connect to 10.3.141.1 if you connected over ap.
