### ISSUE TITLE
Pi4B - RaspAP will either make its own network, or connect to an existing network. Having trouble with wpa_supplicant maybe?

### ISSUE THREAD

**Issue by mw2323** [RaspAP/raspap-webgui#864]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: Latest as of several days ago 
2. Hardware and version: Pi4B
3. RaspAP version: Latest
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? Onboard 
9. Other software or services running with RaspAP? 

## Additional context

I am having issues getting RaspAP to scan for and join existing wifi networks to extend them. I followed all of the instructions very closely and set my wifi country in both wpa_supplicant and raspi-config. I even tried a clean install of Pi OS from the ground up and fully updating everything prior to install. Still, the RaspAP control panel will not scan for networks, and the network icon in the task bar says "No wireless interfaces found". 

I followed this existing issue thread (https://github.com/RaspAP/raspap-webgui/issues/368) and tried the command: 
sudo wpa_supplicant -B -Dnl80211,wext -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0

However, this simply initialized the network connection present in my wpa_supplicant file, while stopping the RaspAP network altogether. I was not able to access the RaspAP control panel at that point either.

I noticed that when trying to check my wifi country in raspi-config at this point, it returns "Could not communicate with wpa_supplicant". Perhaps this is related.

I would really like to get this working to have a portable wifi extender that I can use to extend an internet connection to my other devices, while also utilizing an airplay protocol from my devices to stream media to the Pi plugged into a larger screen via HDMI. Perfect for media streaming at home or on the go, even at a hotel etc.

Thanks for all that you do to support this project, and please let me know if you can help!

**Comment by billz** [comment]
See #656 #833 #596, etc.
