### ISSUE TITLE
how to connect 3g usb dongle to share internet over wlan?

### ISSUE THREAD

**Issue by connected201** [RaspAP/raspap-webgui#871]
hi, i have installed RaspAP v2.6.4
i have modem that work in system:
![image](https://user-images.githubusercontent.com/20506433/115381043-da75e000-a1db-11eb-9585-50eae180d3c0.png)
![image](https://user-images.githubusercontent.com/20506433/115381351-27f24d00-a1dc-11eb-9f84-826ea2f7c3e3.png)
but here i cannot see my 3g modem:
![image](https://user-images.githubusercontent.com/20506433/115381546-58d28200-a1dc-11eb-807f-45740f9c30b9.png)
how to make to receive internet from 3g modem and share to access point?

**Comment by connected201** [comment]
UPD, after enabling Bridged AP mode, i lost access to my raspberry form eth0 raspberry ip was 192.168.100.105, and after enabling, i cannot connect to my web interface!

**Comment by billz** [comment]
Two things: 1) please use the issue template; it's there for a reason. 2) mobile client support is in development for the [Insiders edition](https://docs.raspap.com/insiders/) of RaspAP.

**Comment by billz** [comment]
> after enabling Bridged AP mode, i lost access to my raspberry

https://docs.raspap.com/bridged/#accessing-the-web-interface
