### ISSUE TITLE
Help with Setup

### ISSUE THREAD

**Issue by davidjordan235** [RaspAP/raspap-webgui#89]
Ok, here is what I am looking to do. I am trying to replicate the features for connectivity me (http://www.connectify.me/) using the Raspberry pi3 and the RaspAP web interface. However, I am having trouble even getting the hostAPD running. 

I ran the simple install script. 

Is there any logs, or anything that would tell me the reason hostapd isn't starting. I am very new to this.

Thanks,
DJ

**Comment by billz** [comment]
https://docs.raspap.com/ap-basics/#troubleshooting
