### ISSUE TITLE
Dashboard pages not working

### ISSUE THREAD

**Issue by harunakaze** [RaspAP/raspap-webgui#900]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

Hi, I've just tried to do a fresh install of RaspAP, after rebooting I can see the new hotspot and can connect to it, but when I open Dashboard, the pages seems not working, meaning even if I change pages, it would only show the Dashboard page. The dasboard seems to work though, since I can see my Connected Device.

Kindly help to check, thank you.

## Your environment
1. Operating System: Raspbian 10 
2. Hardware and version: RPi 4 
3. RaspAP version: 2.6.5
4. Followed the project prerequisites? Yes 
5. RaspAP Quick Install or Manual setup? Both
6. Using default configuration? Yes 
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard 
9. Other software or services running with RaspAP? Was Pi-Hole (now uninstalled)

## Steps to reproduce

Do Manual/Quick install, open admin page, and it's not working.

## Screenshots

Change Theme Page:
![image](https://user-images.githubusercontent.com/7606708/118259946-f53a2c80-b4db-11eb-8918-adedb90dd384.png)
About Page:
![image](https://user-images.githubusercontent.com/7606708/118260033-0be08380-b4dc-11eb-98e1-e6e5e7831b0e.png)

## Additional context

Tried both via `10.3.141.1` and it's local IP.
I've already tried reinstalling several times, but still not working.
This is not a fresh install of Rasbian OS, was wondering if I could fix this before doing a fresh install to see if it's solve it.

**Comment by billz** [comment]
> This is not a fresh install of Rasbian OS

Try it with a fresh install per the project requirements. If using a custom directory with the manual steps, be sure to carefully follow these instructions. 

If your problem persists after this, open a new issue.
