### ISSUE TITLE
RaspAP lighttpd configuration overrides other lighttpd vhost / site configs

### ISSUE THREAD

**Issue by reidel** [RaspAP/raspap-webgui#905]
## Checklist

- [ ] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: RPi OS 32-bit
2. Hardware and version: RPi 4, 8GB
3. RaspAP version: 2.6.5
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? Attempted to configure another lighttpd hosted site alongside RaspAP

## Steps to reproduce
a. Install RaspAP
b. configure lighttpd.conf to host another site

## Screenshots
![Screen Shot 2021-05-21 at 9 12 17 AM](https://user-images.githubusercontent.com/963476/119067536-ed671480-ba14-11eb-8d17-097e31cca063.png)
![Screen Shot 2021-05-21 at 9 13 41 AM](https://user-images.githubusercontent.com/963476/119067540-f0620500-ba14-11eb-82ef-86809e6b88c1.png)

## Additional context
In this configuration, I was trying to enable webdav for file drops using lighttpd so as to not have to install more services than needed. However, after a number of tries I noticed the RaspAP default server configuration forces lighttpd to serve the RaspAP site files even on alternative or other host configurations.

I realize this may be solved by following guidelines on hosting multiple sites for lighttpd. (I have yet to try, but in theory it should work. I'm not experienced using lighttpd.) This may simply need a new FAQ section on hosting multiple sites with lighttpd in the RaspAP documentation pages.

```
server.modules = (
        "mod_indexfile",
        "mod_access",
        "mod_alias",
        "mod_redirect",
)

server.document-root        = "/var/www/html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 8888

# strict parsing and normalization of URL for consistency and security
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails
# (might need to explicitly set "url-path-2f-decode" = "disable"
#  if a specific application is encoding URLs inside url-path)
server.http-parseopts = (
  "header-strict"           => "enable",# default
  "host-strict"             => "enable",# default
  "host-normalize"          => "enable",# default
  "url-normalize-unreserved"=> "enable",# recommended highly
  "url-normalize-required"  => "enable",# recommended
  "url-ctrls-reject"        => "enable",# recommended
  "url-path-2f-decode"      => "enable",# recommended highly (unless breaks app)
 #"url-path-2f-reject"      => "enable",
  "url-path-dotseg-remove"  => "enable",# recommended highly (unless breaks app)
 #"url-path-dotseg-reject"  => "enable",
 #"url-query-20-plus"       => "enable",# consistency in query string
)

index-file.names            = ( "index.php", "index.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.conf.pl"
include "/etc/lighttpd/conf-enabled/*.conf"

#server.compat-module-load   = "disable"
server.modules += (
        "mod_compress",
        "mod_dirlisting",
        "mod_staticfile",
        "mod_webdav",
)
#server.bind                             = "10.3.141.1"
$SERVER["socket"] == ":8880" {
  $HTTP["url"] =~ "^/dav($|/)" {
    server.document-root = "/home/user/Public/"
    webdav.activate = "enable"
    webdav.sqlite-db-name = "/var/run/lighttpd/webdav_lock.db"
# commented out due to noticeable authentication errors
# later found out that the RaspAP authentication rules were in effect even on this vhost
#    auth.backend = "htpasswd"
#    auth.backend.htpasswd.userfile = "/var/www/lighttpd/servers/webdav/passwd.dav"
#    auth.require = ( "" => ( "method" => "basic",
#        "realm" => "webdav",
#        "require" => "valid-user" ))
  }
}
```

**Comment by billz** [comment]
The installer prompts you to change the default web location to an arbitrary path of your choice. If you modify this value the default `server.document-root` won't complain about auth errors.
