### ISSUE TITLE
DHCP don't set the ip for dispositives

### ISSUE THREAD

**Issue by crudo0-arch** [RaspAP/raspap-webgui#912]
## Checklist

- [ ] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description
I have a RPI whit sim hat (wwan0) and an alfa usb antenna (wlan1). I don't know why it dosen't work, smartphone don't get the ip. Please help me... my configuration on the gui in the image below, and my log here:

from 10.19.124.244
May 23 17:44:36 dnsmasq[14261]: cached content-autofill.googleapis.com is 172.217.21.74
May 23 17:48:16 dnsmasq[14261]: query[A] tyrqwkpdw from 10.19.124.244
May 23 17:48:16 dnsmasq[14261]: config tyrqwkpdw is NODATA-IPv4
May 23 17:48:16 dnsmasq[14261]: query[A] ojerrzitrug from 10.19.124.244
May 23 17:48:16 dnsmasq[14261]: config ojerrzitrug is NODATA-IPv4
May 23 17:48:16 dnsmasq[14261]: query[A] lsqerooosdmft from 10.19.124.244
May 23 17:48:16 dnsmasq[14261]: config lsqerooosdmft is NODATA-IPv4
May 23 17:48:18 dnsmasq[14261]: exiting on receipt of SIGTERM
May 23 17:48:25 dnsmasq[17504]: started, version 2.80 cachesize 150
May 23 17:48:25 dnsmasq[17504]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile
May 23 17:48:25 dnsmasq[17504]: warning: interface wlan0 does not currently exist
May 23 17:48:25 dnsmasq[17504]: warning: interface eth0 does not currently exist
May 23 17:48:25 dnsmasq[17504]: warning: interface wlan1 does not currently exist
May 23 17:48:25 dnsmasq-dhcp[17504]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:25 dnsmasq-dhcp[17504]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:25 dnsmasq-dhcp[17504]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:25 dnsmasq-dhcp[17504]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:25 dnsmasq[17504]: reading /run/dnsmasq/resolv.conf
May 23 17:48:25 dnsmasq[17504]: using nameserver 151.5.216.25#53
May 23 17:48:25 dnsmasq[17504]: using nameserver 151.5.216.225#53
May 23 17:48:25 dnsmasq[17504]: read /etc/hosts - 5 addresses
May 23 17:48:28 dnsmasq[17504]: read /etc/raspap/adblock/hostnames.txt - 249820 addresses
May 23 17:48:30 dnsmasq[17504]: read /etc/raspap/adblock/hostnames.txt - 249820 addresses
May 23 17:48:30 dnsmasq[17504]: query[A] content-autofill.googleapis.com from 10.19.124.244
May 23 17:48:30 dnsmasq[17504]: forwarded content-autofill.googleapis.com to 151.5.216.25
May 23 17:48:30 dnsmasq[17504]: forwarded content-autofill.googleapis.com to 151.5.216.225
May 23 17:48:30 dnsmasq[17504]: query[A] uqhthgxtr from 10.19.124.244
May 23 17:48:30 dnsmasq[17504]: config uqhthgxtr is NODATA-IPv4
May 23 17:48:30 dnsmasq[17504]: query[A] vhwzosjqmukjpu from 10.19.124.244
May 23 17:48:30 dnsmasq[17504]: config vhwzosjqmukjpu is NODATA-IPv4
May 23 17:48:30 dnsmasq[17504]: query[A] ofogmxtov from 10.19.124.244
May 23 17:48:30 dnsmasq[17504]: config ofogmxtov is NODATA-IPv4
May 23 17:48:30 dnsmasq[17504]: reply content-autofill.googleapis.com is 142.250.180.138
May 23 17:48:38 dnsmasq[17504]: exiting on receipt of SIGTERM
May 23 17:48:48 dnsmasq[17775]: started, version 2.80 cachesize 150
May 23 17:48:48 dnsmasq[17775]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile
May 23 17:48:48 dnsmasq[17775]: warning: interface wlan0 does not currently exist
May 23 17:48:48 dnsmasq[17775]: warning: interface eth0 does not currently exist
May 23 17:48:48 dnsmasq-dhcp[17775]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:48 dnsmasq-dhcp[17775]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:48 dnsmasq-dhcp[17775]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:48 dnsmasq-dhcp[17775]: DHCP, IP range 10.3.141.50 -- 10.3.141.255, lease time 12h
May 23 17:48:48 dnsmasq[17775]: reading /run/dnsmasq/resolv.conf
May 23 17:48:48 dnsmasq[17775]: using nameserver 151.5.216.25#53
May 23 17:48:48 dnsmasq[17775]: using nameserver 151.5.216.225#53
May 23 17:48:48 dnsmasq[17775]: read /etc/hosts - 5 addresses
May 23 17:48:52 dnsmasq[17775]: read /etc/raspap/adblock/hostnames.txt - 249820 addresses
May 23 17:48:53 dnsmasq[17775]: read /etc/raspap/adblock/hostnames.txt - 249820 addresses
May 23 17:48:53 dnsmasq[17775]: query[A] gkfnupi from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config gkfnupi is NODATA-IPv4
May 23 17:48:53 dnsmasq[17775]: query[A] awkrmfonw from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config awkrmfonw is NODATA-IPv4
May 23 17:48:53 dnsmasq[17775]: query[A] spphunnq from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config spphunnq is NODATA-IPv4
May 23 17:48:53 dnsmasq[17775]: query[A] content-autofill.googleapis.com from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: forwarded content-autofill.googleapis.com to 151.5.216.25
May 23 17:48:53 dnsmasq[17775]: forwarded content-autofill.googleapis.com to 151.5.216.225
May 23 17:48:53 dnsmasq[17775]: query[A] content-autofill.googleapis.com from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: query[A] cnmntgnhc from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config cnmntgnhc is NODATA-IPv4
May 23 17:48:53 dnsmasq[17775]: query[A] gnarlqmuix from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config gnarlqmuix is NODATA-IPv4
May 23 17:48:53 dnsmasq[17775]: query[A] ncqsaiuvnra from 10.19.124.244
May 23 17:48:53 dnsmasq[17775]: config ncqsaiuvnra is NODATA-IPv4
May 23 17:48:54 dnsmasq[17775]: reply content-autofill.googleapis.com is 142.250.180.138
May 23 17:49:18 dnsmasq[17775]: query[A] snrtdbqha from 10.19.124.244
May 23 17:49:18 dnsmasq[17775]: config snrtdbqha is NODATA-IPv4
May 23 17:49:18 dnsmasq[17775]: query[A] dhefsadxfhzmotw from 10.19.124.244
May 23 17:49:18 dnsmasq[17775]: config dhefsadxfhzmotw is NODATA-IPv4
May 23 17:49:18 dnsmasq[17775]: query[A] tcxuwrbx from 10.19.124.244
May 23 17:49:18 dnsmasq[17775]: config tcxuwrbx is NODATA-IPv4
May 23 17:49:19 dnsmasq[17775]: query[A] content-autofill.googleapis.com from 10.19.124.244
May 23 17:49:19 dnsmasq[17775]: cached content-autofill.googleapis.com is 142.250.180.138
May 23 17:49:26 dnsmasq[17775]: query[A] ppwhwulgw from 10.19.124.244
May 23 17:49:26 dnsmasq[17775]: config ppwhwulgw is NODATA-IPv4
May 23 17:49:26 dnsmasq[17775]: query[A] hrcnticqjtamivm from 10.19.124.244
May 23 17:49:26 dnsmasq[17775]: config hrcnticqjtamivm is NODATA-IPv4
May 23 17:49:26 dnsmasq[17775]: query[A] eazsewytnij from 10.19.124.244
May 23 17:49:26 dnsmasq[17775]: config eazsewytnij is NODATA-IPv4
May 23 17:49:37 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:49:42 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:49:47 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:49:52 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:01 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:14 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:15 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:15 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:17 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:20 dnsmasq[17775]: query[A] ouciobptxp from 10.19.124.244
May 23 17:50:20 dnsmasq[17775]: config ouciobptxp is NODATA-IPv4
May 23 17:50:20 dnsmasq[17775]: query[A] xcvfdyafnnbmbxm from 10.19.124.244
May 23 17:50:20 dnsmasq[17775]: config xcvfdyafnnbmbxm is NODATA-IPv4
May 23 17:50:20 dnsmasq[17775]: query[A] ylikkklelhagswm from 10.19.124.244
May 23 17:50:20 dnsmasq[17775]: config ylikkklelhagswm is NODATA-IPv4
May 23 17:50:22 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:28 dnsmasq[17775]: query[A] jedswost from 10.19.124.244
May 23 17:50:28 dnsmasq[17775]: config jedswost is NODATA-IPv4
May 23 17:50:28 dnsmasq[17775]: query[A] ksigeospnhmed from 10.19.124.244
May 23 17:50:28 dnsmasq[17775]: config ksigeospnhmed is NODATA-IPv4
May 23 17:50:28 dnsmasq[17775]: query[A] xwkvxvp from 10.19.124.244
May 23 17:50:28 dnsmasq[17775]: config xwkvxvp is NODATA-IPv4
May 23 17:50:31 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:45 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:51 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:52 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:50:57 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:01 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:09 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:22 dnsmasq[17775]: query[A] esxfsmzx from 10.19.124.244
May 23 17:51:22 dnsmasq[17775]: config esxfsmzx is NODATA-IPv4
May 23 17:51:22 dnsmasq[17775]: query[A] wivdracssdsa from 10.19.124.244
May 23 17:51:22 dnsmasq[17775]: config wivdracssdsa is NODATA-IPv4
May 23 17:51:22 dnsmasq[17775]: query[A] cdxozfqlvzsaow from 10.19.124.244
May 23 17:51:22 dnsmasq[17775]: config cdxozfqlvzsaow is NODATA-IPv4
May 23 17:51:25 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:27 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:30 dnsmasq[17775]: query[A] tchcbgdp from 10.19.124.244
May 23 17:51:30 dnsmasq[17775]: config tchcbgdp is NODATA-IPv4
May 23 17:51:30 dnsmasq[17775]: query[A] nslibhg from 10.19.124.244
May 23 17:51:31 dnsmasq[17775]: config nslibhg is NODATA-IPv4
May 23 17:51:31 dnsmasq[17775]: query[A] dvygihkgybfn from 10.19.124.244
May 23 17:51:31 dnsmasq[17775]: config dvygihkgybfn is NODATA-IPv4
May 23 17:51:31 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:35 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:40 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:51:48 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:04 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:06 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:10 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:14 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:22 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:24 dnsmasq[17775]: query[A] mvstvqcmcptkuib from 10.19.124.244
May 23 17:52:24 dnsmasq[17775]: config mvstvqcmcptkuib is NODATA-IPv4
May 23 17:52:24 dnsmasq[17775]: query[A] xwbfbqlpgz from 10.19.124.244
May 23 17:52:24 dnsmasq[17775]: config xwbfbqlpgz is NODATA-IPv4
May 23 17:52:24 dnsmasq[17775]: query[A] lakzogotwsj from 10.19.124.244
May 23 17:52:24 dnsmasq[17775]: config lakzogotwsj is NODATA-IPv4
May 23 17:52:33 dnsmasq[17775]: query[A] fnozpos from 10.19.124.244
May 23 17:52:33 dnsmasq[17775]: config fnozpos is NODATA-IPv4
May 23 17:52:33 dnsmasq[17775]: query[A] esemabu from 10.19.124.244
May 23 17:52:33 dnsmasq[17775]: config esemabu is NODATA-IPv4
May 23 17:52:33 dnsmasq[17775]: query[A] vlmaenloaurrx from 10.19.124.244
May 23 17:52:33 dnsmasq[17775]: config vlmaenloaurrx is NODATA-IPv4
May 23 17:52:37 dnsmasq-dhcp[17775]: no address range available for DHCP request via wlan1
May 23 17:52:49 dnsmasq[17775]: query[PTR] 240.124.19.10.in-addr.arpa from 10.19.124.244
May 23 17:52:49 dnsmasq[17775]: forwarded 240.124.19.10.in-addr.arpa to 151.5.216.25
May 23 17:52:49 dnsmasq[17775]: forwarded 240.124.19.10.in-addr.arpa to 151.5.216.225
May 23 17:52:50 dnsmasq[17775]: reply 10.19.124.240 is NXDOMAIN
May 23 17:52:50 dnsmasq[17775]: query[A] one.one.one.one from 10.19.124.244
May 23 17:52:50 dnsmasq[17775]: forwarded one.one.one.one to 151.5.216.225
May 23 17:52:50 dnsmasq[17775]: query[AAAA] one.one.one.one from 10.19.124.244
May 23 17:52:50 dnsmasq[17775]: forwarded one.one.one.one to 151.5.216.225
May 23 17:52:50 dnsmasq[17775]: reply one.one.one.one is 1.0.0.1
May 23 17:52:50 dnsmasq[17775]: reply one.one.one.one is 1.1.1.1
May 23 17:52:50 dnsmasq[17775]: reply one.one.one.one is 2606:4700:4700::1001
May 23 17:52:50 dnsmasq[17775]: reply one.one.one.one is 2606:4700:4700::1111
May 23 17:52:50 dnsmasq[17775]: query[PTR] 1.0.0.1.in-addr.arpa from 10.19.124.244
May 23 17:52:50 dnsmasq[17775]: forwarded 1.0.0.1.in-addr.arpa to 151.5.216.225
May 23 17:52:50 dnsmasq[17775]: reply 1.0.0.1 is one.one.one.one
![ae934357-0bdd-4618-aa2a-83e500f0dee6](https://user-images.githubusercontent.com/84682960/119467822-2ae5dd80-bd46-11eb-85de-37e8065265a2.jpg)

## Your environment
1. Operating System: RASBIAN 
2. Hardware and version: 
4. Followed the project prerequisites? 
5. RaspAP Quick Install or Manual setup? 
6. Using default configuration? 
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? 
9. Other software or services running with RaspAP?

**Comment by billz** [comment]
https://docs.raspap.com/issues/

**Comment by crudo0-arch** [comment]
There aren't solutions in that, link. I have search how to solve on FAQ and on the docs. 
Why have you closed?
