### ISSUE TITLE
Wifi Client should't sort known wifi by RSSI

### ISSUE THREAD

**Issue by jage0435** [RaspAP/raspap-webgui#925]
## Checklist

- [* ] This is a bug report
- [* ] I have searched this repository for existing issues
- [* ] I checked the FAQ and official documentation before creating this issue
- [* ] I have read and understand the issue reporting guidelines 

## Bug description

I add two WiFi to wpa_supplicant.conf. Web will sort wifi by RSSI by default, but i found it will cause connection funtion connect 
 to wrong wifi client. Because connection script is "sudo wpa-cli -i interface select_network index", so when you sort WiFi by RSSI, it will generate wrong network index if two WiFi's RSSI fluctuating.
I temporarily comment out sortNetworksByRSSI() in /ajax/networking/wifi_stations.php and /includes/configure_client.php. it will fix this bug temporarily .
## Your environment
1. Operating System: **raspi os lite 32 bit** 
2. Hardware and version: RPi Zero W
3. RaspAP version: 2.6.5
4. Followed the project prerequisites? YES
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration?  YES
7. Simultaneous AP and managed mode? Yes
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? 

## Screenshots

![註解 2021-06-02 172907](https://user-images.githubusercontent.com/19412221/120456835-8ceab680-c3c8-11eb-8560-9f26bf3c14a0.jpg)
![註解 2021-06-02 172737](https://user-images.githubusercontent.com/19412221/120456843-8eb47a00-c3c8-11eb-81cf-e07872e1f105.jpg)
![註解 2021-06-02 173005](https://user-images.githubusercontent.com/19412221/120456856-91af6a80-c3c8-11eb-8ff7-75ef167723b5.jpg)

**Comment by billz** [comment]
This project does not currently support multiple wpa_supplicant configurations. It's been discussed elsewhere as a feature request, search for it and add to those conversations, if you wish. Closing this.
