### ISSUE TITLE
N150 Wi-Fi Nano USB Adapter sold out, pls recommend other mini dongle

### ISSUE THREAD

**Issue by dingausmwald** [RaspAP/raspap-webgui#977]
This stick is long sold out and is easily mixed up with the v2 version which isnt working out of the box, seems like even the drivers have to be compiled additionally. Please recommend another (mini) usb dongle.

**Comment by billz** [comment]
See this list of WiFi adapters with in-kernel drivers https://github.com/morrownr/USB-WiFi

I agree with the maintainer that TP-Link and D-Link should generally be avoided.
