### ISSUE TITLE
WiFi client AP mode greyed out even with wifi client configured

### ISSUE THREAD

**Issue by jaune-rouge** [RaspAP/raspap-webgui#986]
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description

Hello, I've been trying to set up "WiFi client AP mode" on a fresh install of raspberry pi os / raspap. My pi is connected to my wifi network and I see that wlan0 is up. I also see hostapd down since I have yet to restart the device. But the option for "WiFi client AP mode" under advanced is still greyed out. Thanks for your help!

## Your environment
1. Operating System:  RPi OS 32-bit Lite 
2. Hardware and version: RPi 3B 
3. RaspAP version: RaspAP v2.6.6 
4. Followed the project prerequisites? Yes 
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes 
7. Simultaneous AP and managed mode? Yes (not yet, but I hope) 
8. Onboard wireless chipset or external adapter? Onboard 
9. Other software or services running with RaspAP? none yet

## Steps to reproduce

I had been following the quick install and the installation steps at https://docs.raspap.com/ap-sta/ until the step to enable "Wifi client AP mode". I'm new to networking and this but if I understood correctly the only thing keeping the option greyed-out would be if the wifi-client wasn't configured with a working network connection, but that is not the case for me.

**Comment by billz** [comment]
RaspAP executes `iwgetid [interface]` to get your wireless network SSID. 

If this doesn't return a network ID, then you don't have an active WiFi client. The status of your wireless client will also be indicated on the dashboard.

**Comment by jaune-rouge** [comment]
@billz Thanks for the reply. That's the thing - `iwgetid wlan0` does return my network name, and my network connection does appear on the dashboard. That side is fine, but for some reason the "WiFi client AP mode" is still greyed out.

**Comment by jaune-rouge** [comment]
![screenshots](https://user-images.githubusercontent.com/17258249/129146428-1ba95d6e-140d-4fce-aede-41ea3738ad4e.jpg)
Here's a screenshot of the dashboard with the advanced hotspot screen superimposed (for fun).

**Comment by jaune-rouge** [comment]
I should also note - that the above I had gotten to before ever rebooting the pi. However for some reason it lost internet connection at some point after this, so I was forced to manually unplug/replug it, which rebooted it - and now the situation is that it is no longer on my wifi network, and instead started transmitting its own raspi-webgui wifi network. If I want to keep trying this headless then I guess I might have to format and reinstall from scratch again.
